name: Publish
on:
  release:
    types: [ published, released ]
jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install prereqs
        run: python -m pip install -U build wheel setuptools

      - name: Build packages
        run: python -m build

      - name: Inspect
        run: ls dist/

      - name: Publish to PyPI
        # Do the actual publishing only for releases, not pre-releases.
        # This can be used to test that the previous steps work.
        if: ${{ github.event.action == 'released' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
